DATA:  {
    symbol: 'RY',
    companyName: 'Royal Bank of Canada',
    primaryExchange: 'c tYNkgoe oaxhcneESk wr',
    calculationPrice: 'close',
    open: null,
    openTime: null,
    close: null,
    closeTime: null,
    high: null,
    low: null,
    latestPrice: 85.5,
    latestSource: 'Close',
    latestTime: 'February 20, 2020',
    latestUpdate: 1598563534245,
    latestVolume: null,
    iexRealtimePrice: 83.745,
    iexRealtimeSize: 54,
    iexLastUpdated: 1606405106700,
    delayedPrice: null,
    delayedPriceTime: null,
    oddLotDelayedPrice: null,
    oddLotDelayedPriceTime: null,
    extendedPrice: null,
    extendedChange: null,
    extendedChangePercent: null,
    extendedPriceTime: null,
    previousClose: 84.14,
    previousVolume: 512041,
    change: -0.12,
    changePercent: -0.00152,
    volume: null,
    iexMarketPercent: 0.01148793195989409,
    iexVolume: 10669,
    avgTotalVolume: 891059,
    iexBidPrice: 0,
    iexBidSize: 0,
    iexAskPrice: 0,
    iexAskSize: 0,
    marketCap: 118521039510,
    peRatio: 12.92,
    week52High: 82.9,
    week52Low: 76.7,
    ytdChange: 0.02084,
    lastTradeTime: 1604585412314,
    isUSMarketOpen: false
  }
  RESPONSE:  {
    status: 200,
    statusText: 'OK',
    headers: {
      server: 'nginx',
      date: 'Fri, 21 Feb 2020 09:09:55 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '995',
      connection: 'close',
      'set-cookie': [
        'ctoken=3b73c5ca470440768fb8263ea5d4ebcb; Max-Age=43200; Path=/; Expires=Fri, 21 Feb 2020 21:09:55 GMT'
      ],
      'iexcloud-messages-used': '1',
      'iexcloud-premium-messages-used': '0',
      'x-content-type-options': 'nosniff',
      'strict-transport-security': 'max-age=15768000',
      'access-control-allow-origin': '*',
      'access-control-allow-credentials': 'true',
      'access-control-allow-methods': 'GET, OPTIONS',
      'access-control-allow-headers': 'Origin, X-Requested-With, Content-Type, Accept'
    },
    config: {
      adapter: [Function: httpAdapter],
      transformRequest: { '0': [Function: transformRequest] },
      transformResponse: { '0': [Function: transformResponse] },
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      headers: {
        Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.18.1'
      },
      method: 'get',
      cancelToken: CancelToken { promise: [Promise] },
      url: 'https://sandbox.iexapis.com/stable/stock/RY/quote?token=Tpk_ffa57ceac12d412f9fe844b2815cf8ee',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype] {
        socket: [Function (anonymous)],
        abort: [Function (anonymous)],
        aborted: [Function (anonymous)],
        error: [Function (anonymous)],
        timeout: [Function (anonymous)],
        prefinish: [Function: requestOnPrefinish]
      },
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'sandbox.iexapis.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object: null prototype],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'sandbox.iexapis.com',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular *1],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 724,
        [Symbol(kHandle)]: [TLSWrap],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object]
      },
      _header: 'GET /stable/stock/RY/quote?token=Tpk_ffa57ceac12d412f9fe844b2815cf8ee HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.18.1\r\n' +
        'Host: sandbox.iexapis.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: Agent {
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object],
        [Symbol(kCapture)]: false
      },
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      path: '/stable/stock/RY/quote?token=Tpk_ffa57ceac12d412f9fe844b2815cf8ee',
      _ended: true,
      res: IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object: null prototype],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 200,
        statusMessage: 'OK',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular *1],
        responseUrl: 'https://sandbox.iexapis.com/stable/stock/RY/quote?token=Tpk_ffa57ceac12d412f9fe844b2815cf8ee',    
        redirects: [],
        [Symbol(kCapture)]: false
      },
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function (anonymous)],
        _currentRequest: [Circular *1],
        _currentUrl: 'https://sandbox.iexapis.com/stable/stock/RY/quote?token=Tpk_ffa57ceac12d412f9fe844b2815cf8ee',    
        [Symbol(kCapture)]: false
      },
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        accept: [Array],
        'user-agent': [Array],
        host: [Array]
      }
    },
    data: {
      symbol: 'RY',
      companyName: 'Royal Bank of Canada',
      primaryExchange: 'c tYNkgoe oaxhcneESk wr',
      calculationPrice: 'close',
      open: null,
      openTime: null,
      close: null,
      closeTime: null,
      high: null,
      low: null,
      latestPrice: 85.5,
      latestSource: 'Close',
      latestTime: 'February 20, 2020',
      latestUpdate: 1598563534245,
      latestVolume: null,
      iexRealtimePrice: 83.745,
      iexRealtimeSize: 54,
      iexLastUpdated: 1606405106700,
      delayedPrice: null,
      delayedPriceTime: null,
      oddLotDelayedPrice: null,
      oddLotDelayedPriceTime: null,
      extendedPrice: null,
      extendedChange: null,
      extendedChangePercent: null,
      extendedPriceTime: null,
      previousClose: 84.14,
      previousVolume: 512041,
      change: -0.12,
      changePercent: -0.00152,
      volume: null,
      iexMarketPercent: 0.01148793195989409,
      iexVolume: 10669,
      avgTotalVolume: 891059,
      iexBidPrice: 0,
      iexBidSize: 0,
      iexAskPrice: 0,
      iexAskSize: 0,
      marketCap: 118521039510,
      peRatio: 12.92,
      week52High: 82.9,
      week52Low: 76.7,
      ytdChange: 0.02084,
      lastTradeTime: 1604585412314,
      isUSMarketOpen: false
    }
  }